---
title: "An치lisis de comportamiento de clientes y oportunidades de promoci칩n"
format: 
    html:
         page-layout: article
toc: false
author: 
  - name: "Angel Merino Cede침o"
    email: "acedeno00@gmail.com"     # Aparece un icono de correo
    url: "https://www.linkedin.com/in/anmerino-pnd"          # Aparece icono de web si quieres
    affiliations:
        - name : "[游늯 CV](https://unisonmx-my.sharepoint.com/:w:/g/personal/a218204710_unison_mx/EYLVn5p-js9Hh7hr8HmUKOgBZq5L1wHwtZzyjEZG_SeUGA?e=Q7U9pP)"
  - name: "Gerardo Leyva Conde"
  - name: "Roberto Navarro Bartolini"
  - name: "Abraham Rojo Salazar"
  - name: "Oscar Esquer Vazquez"
date: last-modified
date-format: long
lang: es
---

::: {style="text-align: justify"}
## Introducci칩n

Este proyecto se enfoca en el desarrollo de un sistema de an치lisis e inteligencia de negocios basado en los patrones de b칰squeda y compras de los clientes de CT Internacional. A trav칠s del procesamiento de datos transaccionales hist칩ricos, buscamos transformar un enfoque de marketing en una estrategia proactiva, personalizada y basada en el comportamiento real del consumidor.

El proyecto se divide en las siguientes fases iniciales:

1. **Comprensi칩n del negocio:** Definir el problema central de la desalineaci칩n entre las campa침as de proveedores y los intereses reales de los clientes de CT Internacional.

2. **Extracci칩n y comprensi칩n de los datos:** Recolecci칩n de un hist칩rico de transacciones (ventas, fechas, ID de clientes, categor칤as de productos, marcas, b칰squedas) y validaci칩n de la integridad de la informaci칩n.

3. **Ingenier칤a de caracter칤sticas:** Creaci칩n de nuevas m칠tricas de valor a partir de los datos crudos, tales como: d칤as desde la 칰ltima compra (Recency), frecuencia de compra o de b칰squeda, ticket promedio y dependencia de categor칤a.

4. **An치lisis exploratorio y visualizaci칩n (EDA & Dashboards):** Construcci칩n de herramientas visuales (mockups y dashboards) que expongan de manera clara problemas como la fuga de clientes, el inventario estancado, oportunidades de venta cruzada, presencia de productos por categor칤a, m치s vendidos y no tan vendidos.

5. **Segmentaci칩n avanzada (fase 2)** Aplicaci칩n de modelos de aprendizaje no supervisado (como K-Means o an치lisis RFM) para agrupar clientes seg칰n su comportamiento y rentabilidad.

A trav칠s de estas fases, buscamos proporcionar a los equipos de ventas y marketing herramientas accionables que mejoren la retenci칩n de clientes, aumenten la eficacia de las promociones y fortalezcan las negociaciones con los proveedores basados en datos duros.
:::