project:
  type: website
  output-dir: ../docs
  render:
    - 0_home.qmd
    - 1_comprension.qmd
    - 2_exploracion_datos.qmd
    - 3_analisis_rfm.qmd
    - 4_segmentacion_clientes.qmd
    - 5_market_basket.qmd
    - 6_estacionalidad_segmentos.qmd
    - 7_persistencia_mlops.qmd
    - 8_dashboard_pulse.qmd
    - 9_vision_y_futuro.qmd

website:
  favicon: ./images/favicon.png # Descomentar si hay favicon
  navbar:
    logo: ./images/ctlogo.png # Descomentar si hay logo
    left:
      - href: 0_home.qmd
        text: Inicio
      - href: 1_comprension.qmd
        text: Comprensión del Negocio
      - href: 2_exploracion_datos.qmd
        text: Exploración de Datos
      - href: 3_analisis_rfm.qmd
        text: Análisis RFM
      - href: 4_segmentacion_clientes.qmd
        text: Segmentación
      - href: 5_market_basket.qmd
        text: Market Basket
      - href: 6_estacionalidad_segmentos.qmd
        text: Estacionalidad
      - href: 7_persistencia_mlops.qmd
        text: MLOps
      - href: 8_dashboard_pulse.qmd
        text: Dashboard
      - href: 9_vision_y_futuro.qmd
        text: Visión y Futuro
      
  back-to-top-navigation: true
      
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css # Descomentar si añadimos CSS personalizado
    toc: true
    execute:
      echo: true # True para mostrar el código de los notebooks

diagram:
  mermaid:
    theme: neutral
    
lang: es